export const EMAIL_LOGIN = "EMAIL_LOGIN";
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const SIGNUP = "SIGNUP";

export const CONVERT_TO_ICEBERG_REQUEST = 'CONVERT_TO_ICEBERG_REQUEST';
export const DATA_FILES_TO_ICEBERG = 'DATA_FILES_TO_ICEBERG';