export const EMAIL_LOGIN = "EMAIL_LOGIN";
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const SIGNUP = "SIGNUP";

export const BIGQUERY_TO_ICEBERG = 'BIGQUERY_TO_ICEBERG';
export const DATA_FILES_TO_ICEBERG = 'DATA_FILES_TO_ICEBERG';
export const POSTGERS_TO_ICEBERG = 'POSTGERS_TO_ICEBERG';